default:
  image: frostmonster/sharlabr_c_image:latest

stages:
  - lint

lint-job:
  stage: lint
  script:
    - cp ./materials/linters/.clang-format ./src/.clang-format
    - cd ./src/
    - if [ -f *.cc ] || [ -f *.h ]; then if $(clang-format -n *.cc *.h); then  clang-format -i *.cc *.h; fi; fi
    - rm .clang-format
