stages:
  - lint

lint-job:
  stage: lint
  script:
    - cp ./materials/linters/.clang-format ./src/.clang-format
    - cd ./src/
    - if $(find . -name "*.cpp" -exec clang-format -n {} \;); exit 1; fi
