stages:
  - lint

lint-job:
  stage: lint
  script:
    - cp ./materials/linters/.clang-format ./src/.clang-format
    - cd ./src/
    - if [ -f *.cc ] || [ -f *.h ]; then if $(clang-format -n *.cc *.hpp *.cpp *.tpp *.h *.c); then  clang-format -i *.cc *.hpp *.cpp *.tpp *.h *.c; fi; fi
    - rm .clang-format
