default:
  image: frostmonster/sharlabr_c_image:latest

stages:
  - lint

lint-job:
  stage: lint
  script:
    - cp ./materials/linters/.clang-format ./src/.clang-format
    - cd ./src/
    - clang-format -n *.cc *.hpp *.cpp *.tpp
    - rm .clang-format
